package com.s4s.charity.candidatesvc.model;

import org.springframework.data.annotation.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;



@DynamoDBTable(tableName = "pa_candidate_info")
public class PACandidateInfo {
	
	@Id
	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	private String id;
	
	@DynamoDBAttribute
	private String address;
	@DynamoDBAttribute
	private String city;
	@DynamoDBAttribute
	private String constituency;
	@DynamoDBAttribute
	private String criminal_case;
	@DynamoDBAttribute
	private String education;
	@DynamoDBAttribute(attributeName = "first_name")
	private String firstName;
	@DynamoDBAttribute
	private String last_name;
	@DynamoDBAttribute
	private String middle_name;
	@DynamoDBAttribute
	private String political_party;
	@DynamoDBAttribute
	private String self_profession;
	@DynamoDBAttribute
	private String spouse_profession;
	@DynamoDBAttribute
	private String state;
	@DynamoDBAttribute
	private String total_asset;
	@DynamoDBAttribute
	private String total_liabilities;
	@DynamoDBAttribute
	private String vision_statement;
	@DynamoDBAttribute
	private String yearly_income;
	@DynamoDBAttribute(attributeName = "zip_code")
	private String zipCode;
	/**
	 * @return the id
	 */
	public String getId() {
		return id;
	}
	/**
	 * @param id the id to set
	 */
	public void setId(String id) {
		this.id = id;
	}
	/**
	 * @return the address
	 */
	public String getAddress() {
		return address;
	}
	/**
	 * @param address the address to set
	 */
	public void setAddress(String address) {
		this.address = address;
	}
	/**
	 * @return the city
	 */
	public String getCity() {
		return city;
	}
	/**
	 * @param city the city to set
	 */
	public void setCity(String city) {
		this.city = city;
	}
	/**
	 * @return the constituency
	 */
	public String getConstituency() {
		return constituency;
	}
	/**
	 * @param constituency the constituency to set
	 */
	public void setConstituency(String constituency) {
		this.constituency = constituency;
	}
	/**
	 * @return the criminal_case
	 */
	public String getCriminal_case() {
		return criminal_case;
	}
	/**
	 * @param criminal_case the criminal_case to set
	 */
	public void setCriminal_case(String criminal_case) {
		this.criminal_case = criminal_case;
	}
	/**
	 * @return the education
	 */
	public String getEducation() {
		return education;
	}
	/**
	 * @param education the education to set
	 */
	public void setEducation(String education) {
		this.education = education;
	}
	/**
	 * @return the firstName
	 */
	public String getFirstName() {
		return firstName;
	}
	/**
	 * @param firstName the firstName to set
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	/**
	 * @return the last_name
	 */
	public String getLast_name() {
		return last_name;
	}
	/**
	 * @param last_name the last_name to set
	 */
	public void setLast_name(String last_name) {
		this.last_name = last_name;
	}
	/**
	 * @return the middle_name
	 */
	public String getMiddle_name() {
		return middle_name;
	}
	/**
	 * @param middle_name the middle_name to set
	 */
	public void setMiddle_name(String middle_name) {
		this.middle_name = middle_name;
	}
	/**
	 * @return the political_party
	 */
	public String getPolitical_party() {
		return political_party;
	}
	/**
	 * @param political_party the political_party to set
	 */
	public void setPolitical_party(String political_party) {
		this.political_party = political_party;
	}
	/**
	 * @return the self_profession
	 */
	public String getSelf_profession() {
		return self_profession;
	}
	/**
	 * @param self_profession the self_profession to set
	 */
	public void setSelf_profession(String self_profession) {
		this.self_profession = self_profession;
	}
	/**
	 * @return the spouse_profession
	 */
	public String getSpouse_profession() {
		return spouse_profession;
	}
	/**
	 * @param spouse_profession the spouse_profession to set
	 */
	public void setSpouse_profession(String spouse_profession) {
		this.spouse_profession = spouse_profession;
	}
	/**
	 * @return the state
	 */
	public String getState() {
		return state;
	}
	/**
	 * @param state the state to set
	 */
	public void setState(String state) {
		this.state = state;
	}
	/**
	 * @return the total_asset
	 */
	public String getTotal_asset() {
		return total_asset;
	}
	/**
	 * @param total_asset the total_asset to set
	 */
	public void setTotal_asset(String total_asset) {
		this.total_asset = total_asset;
	}
	/**
	 * @return the total_liabilities
	 */
	public String getTotal_liabilities() {
		return total_liabilities;
	}
	/**
	 * @param total_liabilities the total_liabilities to set
	 */
	public void setTotal_liabilities(String total_liabilities) {
		this.total_liabilities = total_liabilities;
	}
	/**
	 * @return the vision_statement
	 */
	public String getVision_statement() {
		return vision_statement;
	}
	/**
	 * @param vision_statement the vision_statement to set
	 */
	public void setVision_statement(String vision_statement) {
		this.vision_statement = vision_statement;
	}
	/**
	 * @return the yearly_income
	 */
	public String getYearly_income() {
		return yearly_income;
	}
	/**
	 * @param yearly_income the yearly_income to set
	 */
	public void setYearly_income(String yearly_income) {
		this.yearly_income = yearly_income;
	}
	/**
	 * @return the zip_code
	 */
	public String getZip_code() {
		return zipCode;
	}
	/**
	 * @param zip_code the zip_code to set
	 */
	public void setZip_code(String zip_code) {
		this.zipCode = zip_code;
	}
	

	
}
